version: "3"

services:
  client:
    stdin_open: true
    tty: true
    image: alexbenzar/client
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - mern-app
  server:
    image: alexbenzar/server
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - mern-app
  database:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
